// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getHouseInfo.proto

package getHouseInfo

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GetHouseInfo service

func NewGetHouseInfoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GetHouseInfo service

type GetHouseInfoService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
}

type getHouseInfoService struct {
	c    client.Client
	name string
}

func NewGetHouseInfoService(name string, c client.Client) GetHouseInfoService {
	return &getHouseInfoService{
		c:    c,
		name: name,
	}
}

func (c *getHouseInfoService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "GetHouseInfo.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetHouseInfo service

type GetHouseInfoHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
}

func RegisterGetHouseInfoHandler(s server.Server, hdlr GetHouseInfoHandler, opts ...server.HandlerOption) error {
	type getHouseInfo interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
	}
	type GetHouseInfo struct {
		getHouseInfo
	}
	h := &getHouseInfoHandler{hdlr}
	return s.Handle(s.NewHandler(&GetHouseInfo{h}, opts...))
}

type getHouseInfoHandler struct {
	GetHouseInfoHandler
}

func (h *getHouseInfoHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.GetHouseInfoHandler.Call(ctx, in, out)
}
