// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/orders.proto

package orders

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Orders service

func NewOrdersEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Orders service

type OrdersService interface {
	CreateOrder(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetOrderInfo(ctx context.Context, in *GetReq, opts ...client.CallOption) (*GetResp, error)
	UpdateStatus(ctx context.Context, in *UpdateReq, opts ...client.CallOption) (*UpdateResp, error)
}

type ordersService struct {
	c    client.Client
	name string
}

func NewOrdersService(name string, c client.Client) OrdersService {
	return &ordersService{
		c:    c,
		name: name,
	}
}

func (c *ordersService) CreateOrder(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Orders.CreateOrder", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersService) GetOrderInfo(ctx context.Context, in *GetReq, opts ...client.CallOption) (*GetResp, error) {
	req := c.c.NewRequest(c.name, "Orders.GetOrderInfo", in)
	out := new(GetResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersService) UpdateStatus(ctx context.Context, in *UpdateReq, opts ...client.CallOption) (*UpdateResp, error) {
	req := c.c.NewRequest(c.name, "Orders.UpdateStatus", in)
	out := new(UpdateResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Orders service

type OrdersHandler interface {
	CreateOrder(context.Context, *Request, *Response) error
	GetOrderInfo(context.Context, *GetReq, *GetResp) error
	UpdateStatus(context.Context, *UpdateReq, *UpdateResp) error
}

func RegisterOrdersHandler(s server.Server, hdlr OrdersHandler, opts ...server.HandlerOption) error {
	type orders interface {
		CreateOrder(ctx context.Context, in *Request, out *Response) error
		GetOrderInfo(ctx context.Context, in *GetReq, out *GetResp) error
		UpdateStatus(ctx context.Context, in *UpdateReq, out *UpdateResp) error
	}
	type Orders struct {
		orders
	}
	h := &ordersHandler{hdlr}
	return s.Handle(s.NewHandler(&Orders{h}, opts...))
}

type ordersHandler struct {
	OrdersHandler
}

func (h *ordersHandler) CreateOrder(ctx context.Context, in *Request, out *Response) error {
	return h.OrdersHandler.CreateOrder(ctx, in, out)
}

func (h *ordersHandler) GetOrderInfo(ctx context.Context, in *GetReq, out *GetResp) error {
	return h.OrdersHandler.GetOrderInfo(ctx, in, out)
}

func (h *ordersHandler) UpdateStatus(ctx context.Context, in *UpdateReq, out *UpdateResp) error {
	return h.OrdersHandler.UpdateStatus(ctx, in, out)
}
